ALTER TABLE clips ADD COLUMN was_compressed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clips ADD COLUMN original_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clips ADD COLUMN compressed_size INTEGER NOT NULL DEFAULT 0;
