//! Auto-detection of the built-in system categories.
//!
//! This is the single source of truth for automatic tagging. It replaces the
//! keyword-and-prefix heuristics that previously lived in the search classifier,
//! which ran on the same insert path and produced overlapping labels.

use regex::Regex;
use std::sync::OnceLock;

/// Every system category, in the order detection is attempted.
///
/// Order matters: a URL can contain an `@`, and a file path can contain braces,
/// so the more specific shapes are tested first.
pub const SYSTEM_CATEGORIES: [&str; 6] =
    ["Links", "Email", "Phone", "File Path", "Color", "Code"];

/// Settings key holding the enable flag for a system category.
///
/// Folds the display name to lowercase with non-alphanumeric runs replaced by an
/// underscore, so "File Path" becomes `category_enabled_file_path`. The seeded
/// keys in migration 0006 are generated by the same rule.
pub fn enabled_setting_key(category: &str) -> String {
    let slug: String = category
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    format!("category_enabled_{slug}")
}

/// Detect which system category a clip belongs to, if any.
///
/// Returns `None` for content that matches nothing, which is left untagged.
pub fn detect_system_category(content: &str) -> Option<&'static str> {
    let trimmed = content.trim();
    if trimmed.is_empty() {
        return None;
    }

    if is_link(trimmed) {
        return Some("Links");
    }
    if is_email(trimmed) {
        return Some("Email");
    }
    if is_phone(trimmed) {
        return Some("Phone");
    }
    if is_file_path(trimmed) {
        return Some("File Path");
    }
    if is_color(trimmed) {
        return Some("Color");
    }
    if is_code(content) {
        return Some("Code");
    }
    None
}

fn is_link(s: &str) -> bool {
    static RE: OnceLock<Option<Regex>> = OnceLock::new();
    matches(&RE, r"(?i)^(https?://|ftp://|www\.)[^\s]{4,}$", s)
}

fn is_email(s: &str) -> bool {
    static RE: OnceLock<Option<Regex>> = OnceLock::new();
    matches(&RE, r"^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$", s)
}

/// Common written phone shapes: +1-234-567-8900, (234) 567-8900, 234.567.8900.
fn is_phone(s: &str) -> bool {
    static RE: OnceLock<Option<Regex>> = OnceLock::new();
    // Require enough digits that a bare year or house number does not qualify.
    if s.chars().filter(char::is_ascii_digit).count() < 7 {
        return false;
    }
    matches(
        &RE,
        r"^\+?[(]?[0-9]{1,4}[)]?[-\s\.]?[(]?[0-9]{1,3}[)]?[-\s\.]?[0-9]{3,4}[-\s\.]?[0-9]{3,5}$",
        s,
    )
}

fn is_file_path(s: &str) -> bool {
    if s.contains('\n') || s.contains(' ') && s.len() > 260 {
        return false;
    }
    let lower = s.to_ascii_lowercase();
    let unix = lower.starts_with('/') || lower.starts_with("~/") || lower.starts_with("./")
        || lower.starts_with("../");
    let windows = lower.len() > 3
        && lower.as_bytes()[0].is_ascii_alphabetic()
        && lower.as_bytes()[1] == b':'
        && (lower.as_bytes()[2] == b'\\' || lower.as_bytes()[2] == b'/');
    (unix || windows) && !s.contains('\n')
}

fn is_color(s: &str) -> bool {
    static RE: OnceLock<Option<Regex>> = OnceLock::new();
    matches(&RE, r"^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$", s)
}

/// Heuristic: source code is multi-line and carries at least one structural cue.
///
/// The multi-line requirement is what keeps ordinary prose containing a word
/// like "class" from being tagged as code.
fn is_code(s: &str) -> bool {
    if s.lines().count() <= 2 {
        return false;
    }
    let has_block = s.contains('{') && s.contains('}');
    let has_keyword = [
        "fn ", "def ", "function ", "class ", "import ", "#include", " => ", "return ",
        "struct ", "public ", "private ", "const ", "</",
    ]
    .iter()
    .any(|kw| s.contains(kw));
    let has_statement = s.contains('=') && s.contains(';');
    has_block || has_keyword || has_statement
}

/// Compile once and match. A regex that fails to compile disables its rule
/// rather than bringing the clipboard watcher down.
fn matches(cell: &OnceLock<Option<Regex>>, pattern: &'static str, s: &str) -> bool {
    cell.get_or_init(|| match Regex::new(pattern) {
        Ok(re) => Some(re),
        Err(e) => {
            tracing::error!("category_detect: pattern failed to compile: {e}");
            None
        }
    })
    .as_ref()
    .is_some_and(|re| re.is_match(s))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_https_and_http_links() {
        assert_eq!(detect_system_category("https://github.com/user/repo"), Some("Links"));
        assert_eq!(detect_system_category("http://example.com"), Some("Links"));
        assert_eq!(detect_system_category("  https://example.com/a  "), Some("Links"));
    }

    #[test]
    fn plain_text_is_not_a_link() {
        assert_eq!(detect_system_category("just some ordinary words"), None);
        assert_eq!(detect_system_category("read https://example.com later"), None);
    }

    #[test]
    fn detects_valid_email_addresses() {
        assert_eq!(detect_system_category("user@example.com"), Some("Email"));
        assert_eq!(detect_system_category("first.last+tag@sub.example.co.uk"), Some("Email"));
    }

    #[test]
    fn partial_emails_are_not_email() {
        for s in ["user@", "@example.com", "user@example", "a b@c.com"] {
            assert_ne!(detect_system_category(s), Some("Email"), "wrongly matched: {s}");
        }
    }

    #[test]
    fn detects_common_phone_formats() {
        for s in ["+1-234-567-8900", "(234) 567-8900", "234.567.8900", "234-567-8900"] {
            assert_eq!(detect_system_category(s), Some("Phone"), "missed: {s}");
        }
    }

    /// Short digit strings are years, counts and house numbers far more often
    /// than they are phone numbers.
    #[test]
    fn short_numbers_are_not_phone() {
        for s in ["2026", "42", "1-2-3"] {
            assert_ne!(detect_system_category(s), Some("Phone"), "wrongly matched: {s}");
        }
    }

    #[test]
    fn detects_file_paths() {
        assert_eq!(detect_system_category("/home/user/notes.txt"), Some("File Path"));
        assert_eq!(detect_system_category("~/projects/synaptclip"), Some("File Path"));
        assert_eq!(detect_system_category("./src/main.rs"), Some("File Path"));
        assert_eq!(detect_system_category("C:\\Users\\me\\file.txt"), Some("File Path"));
    }

    #[test]
    fn detects_hex_colors() {
        assert_eq!(detect_system_category("#fff"), Some("Color"));
        assert_eq!(detect_system_category("#1a2b3c"), Some("Color"));
        assert_ne!(detect_system_category("#xyz123"), Some("Color"));
    }

    #[test]
    fn detects_multi_line_code_blocks() {
        let code = "fn main() {\n    let x = 1;\n    println!(\"{}\", x);\n}";
        assert_eq!(detect_system_category(code), Some("Code"));

        let js = "function add(a, b) {\n  return a + b;\n}\n";
        assert_eq!(detect_system_category(js), Some("Code"));
    }

    #[test]
    fn short_plain_text_is_not_code() {
        assert_eq!(detect_system_category("hello world"), None);
        assert_eq!(detect_system_category("a class act"), None);
        assert_eq!(detect_system_category("one\ntwo"), None);
    }

    #[test]
    fn empty_and_whitespace_match_nothing() {
        assert_eq!(detect_system_category(""), None);
        assert_eq!(detect_system_category("   \n  "), None);
    }

    #[test]
    fn setting_keys_match_the_seeded_names() {
        assert_eq!(enabled_setting_key("Links"), "category_enabled_links");
        assert_eq!(enabled_setting_key("File Path"), "category_enabled_file_path");
        assert_eq!(enabled_setting_key("Color"), "category_enabled_color");
    }

    /// Every category the detector can return must be one the migration seeded,
    /// otherwise its toggle would have no row to read.
    #[test]
    fn every_detected_category_is_a_known_system_category() {
        for sample in [
            "https://example.com/x",
            "user@example.com",
            "+1-234-567-8900",
            "/home/user/a.txt",
            "#1a2b3c",
            "fn a() {\n let x = 1;\n}",
        ] {
            let found = detect_system_category(sample).expect("sample should match");
            assert!(SYSTEM_CATEGORIES.contains(&found), "unknown category: {found}");
        }
    }
}
